rails_first_assignment/config/routes.rb
RailsFirstAssignment::Application.routes.draw do
  resources :storms

end

rails_first_assignment/app/models/storm.rb
class Storm < ActiveRecord::Base
end

rails_first_assignment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails_first_assignment/app/controllers/storms_controller.rb
class StormsController < ApplicationController
  # GET /storms
  # GET /storms.json
  def index
    @storms = Storm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @storms }
    end
  end

  # GET /storms/1
  # GET /storms/1.json
  def show
    @storm = Storm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @storm }
    end
  end

  # GET /storms/new
  # GET /storms/new.json
  def new
    @storm = Storm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @storm }
    end
  end

  # GET /storms/1/edit
  def edit
    @storm = Storm.find(params[:id])
  end

  # POST /storms
  # POST /storms.json
  def create
    @storm = Storm.new(params[:storm])

    respond_to do |format|
      if @storm.save
        format.html { redirect_to @storm, notice: 'Storm was successfully created.' }
        format.json { render json: @storm, status: :created, location: @storm }
      else
        format.html { render action: "new" }
        format.json { render json: @storm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /storms/1
  # PUT /storms/1.json
  def update
    @storm = Storm.find(params[:id])

    respond_to do |format|
      if @storm.update_attributes(params[:storm])
        format.html { redirect_to @storm, notice: 'Storm was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @storm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storms/1
  # DELETE /storms/1.json
  def destroy
    @storm = Storm.find(params[:id])
    @storm.destroy

    respond_to do |format|
      format.html { redirect_to storms_url }
      format.json { head :ok }
    end
  end
end

rails_first_assignment/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_first_assignment/app/helpers/storms_helper.rb
module StormsHelper
end

rails_first_assignment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFirstAssignment</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails_first_assignment/app/views/storms/_form.html.erb
<%= form_for(@storm) do |f| %>
  <% if @storm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storm.errors.count, "error") %> prohibited this storm from being saved:</h2>

      <ul>
      <% @storm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :snowfall %><br />
    <%= f.text_field :snowfall %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_first_assignment/app/views/storms/edit.html.erb
<h1>Editing storm</h1>

<%= render 'form' %>

<%= link_to 'Show', @storm %> |
<%= link_to 'Back', storms_path %>

rails_first_assignment/app/views/storms/index.html.erb
<h1>Listing storms</h1>

<table>
  <tr>
    <th>Day</th>
    <th>Snowfall</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @storms.each do |storm| %>
  <tr>
    <td><%= storm.day %></td>
    <td><%= storm.snowfall %></td>
    <td><%= link_to 'Show', storm %></td>
    <td><%= link_to 'Edit', edit_storm_path(storm) %></td>
    <td><%= link_to 'Destroy', storm, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Storm', new_storm_path %>

rails_first_assignment/app/views/storms/new.html.erb
<h1>New storm</h1>

<%= render 'form' %>

<%= link_to 'Back', storms_path %>

rails_first_assignment/app/views/storms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @storm.day %>
</p>

<p>
  <b>Snowfall:</b>
  <%= @storm.snowfall %>
</p>


<%= link_to 'Edit', edit_storm_path(@storm) %> |
<%= link_to 'Back', storms_path %>